### ISSUE TITLE
日常答疑问题记录

### ISSUE THREAD

**Issue by ZQKC** [didi/LogiKM#192]

**Comment by ZQKC** [comment]
Q：如何修改admin用户的默认密码？
A：在运维管控-平台配置-用户配置里。

**Comment by ZQKC** [comment]
Q：平台哪些指标是需要依赖滴滴内部kafka-gateway的？
A：后续出个文档&在产品具体位置上进行说明。

**Comment by ZQKC** [comment]
Q：监控告警中的新增告警组如何添加？
A：需要结合夜莺才可以实现具体的监控告警功能，包括这里的告警组。具体的可以看一下FAQ。

**Comment by ZQKC** [comment]
Q：Topic保持时间是否可以修改？
A：可以修改的，在运维管控-Topic信息那块可以进行修改。

**Comment by yuanzy1994** [comment]
get jmx connector failed??  what's questions in my log_warn?

**Comment by ZQKC** [comment]
> get jmx connector failed?? what's questions in my log_warn?

failed to get jmx connector will cause to get metrics failed，and you can try to solve by  https://github.com/didi/Logi-KafkaManager/blob/master/docs/user_guide/faq.md
