### ISSUE TITLE
在 “专家服务”里面，多次点击菜单的关闭，打开，会出现图片所示情况。应该是一个bug

### ISSUE THREAD

**Issue by Hongten** [didi/LogiKM#218]
What happened:
左侧菜单出现多个图标

What you expected to happen:
其他模块左侧菜单多长打开，关闭后，没有出现增加多个图标的情况

How to reproduce it (as minimally and precisely as possible):
在 “专家服务”里面，多次点击菜单的关闭，打开

Anything else we need to know?:

Environment:

Nightingale Version (./n9e-rdb -v):
OS Version (uname -a):
Logs (stdout/error/warning/http.request/http.response):
Others:
http://117.51.146.109:8080

![image](https://user-images.githubusercontent.com/3076703/113260025-604eeb80-9300-11eb-91cc-33e09dd1a871.png)

**Comment by ZQKC** [comment]
新版本可以再试一下，看是否有该问题，我这边测试多次没有复现

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题
