### ISSUE TITLE
Topic 基本信息完善一些统计指标

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#235]
参考 Yahoo 的 CMAK 的 Topic View:

![2021-04-22 13-42-29屏幕截图](https://user-images.githubusercontent.com/11460848/115661790-9831d780-a370-11eb-9655-a32e9136e346.png)

Logi 能否在 Topic 基本信息区域加上部分统计信息，比如:

- Sum of partition offsets
- Brokers Leader Skewed %

**Comment by ZQKC** [comment]
这些是用在什么情况下呢？展示什么数据以及指标更多的是出于场景的考虑，这块辛苦也告知一下这些指标在你们实际中使用的场景

**Comment by cobolbaby** [comment]
核心是以下两个指标:
- Sum of partition offsets 可以说明当前TOPIC总共接收了多少消息，这个比分别查看分区记录数更加直接
- Broker Leader Skewed % 可以直接说明是否需要重分布
  - 或许是使用 Logi-KM 的次数还不多，当前没有看到其怎么突显该信息

**Comment by ZQKC** [comment]
Sum of partition offsets：这块有什么实际的使用场景么？或者说为什么需要查看这个数据，平时什么情况下需要知道这个数据？
Broker Leader Skewed %：这块有一个Topic Broker信息页面，这个信息就可以看到在Region维度上的leader分布情况，也可以很快发现不均衡的情况。

**Comment by cobolbaby** [comment]
> Sum of partition offsets：这块有什么实际的使用场景么？或者说为什么需要查看这个数据，平时什么情况下需要知道这个数据？

- 在功能开发调试阶段，用户可以看消息是否上传了
- 在生产阶段，用户可以看到自己到底总共推送了多少消息

>  Broker Leader Skewed %：这块有一个Topic Broker信息页面，这个信息就可以看到在Region维度上的leader分布情况，也可以很快发现不均衡的情况。

- Region 维度的话，我理解为全局是否有 Leader 倾斜，但不代表某个 Topic 是否有倾斜

**Comment by ZQKC** [comment]
@ZHAOYINRUI 第一个寅锐可以看一下啊，我觉得这么说也算合理。
第二个是指单个Topic在Region内是否有倾斜，一般我们不会去看单个Topic在集群维度是否有倾斜。我们期望是通过Region做一定的资源隔离。

**Comment by cobolbaby** [comment]
> 第二个是指单个Topic在Region内是否有倾斜，一般我们不会去看单个Topic在集群维度是否有倾斜。我们期望是通过Region做一定的资源隔离。

的确，如果单一Topic是否存在倾斜不太重要的话，那再问一下，怎么看Region是否存在Leader的倾斜，我只看到了有Leader Balance选项，并没有看到哪能看出来倾斜不倾斜。

**Comment by ZQKC** [comment]
Topic详情中的Broker信息

**Comment by cobolbaby** [comment]
Topic详情中的Broker信息那块也显示不出来Region级别是否存在倾斜，只能显示出来Topic级别的，是否可以在"集群列表 > 某集群 > Borker信息" 下面的列表增加一列 -- Leader数量?

**Comment by ZQKC** [comment]
Broker列表展示Leader数量的需求，后端应该已经把数据返回了，只是前端还没有展示出来，老哥有兴趣的话，来个前端的PR展示一下😊

**Comment by cobolbaby** [comment]
讨论到最后有两个指标可能需要完善:

- Sum of partition offsets -- Topic基本信息页面
- Leader of broker -- 集群Broker列表页面

能否请前端开发提供一下支持？

**Comment by ZQKC** [comment]
> 讨论到最后有两个指标可能需要完善:
> 
> * Sum of partition offsets -- Topic基本信息页面
> * Leader of broker -- 集群Broker列表页面
> 
> 能否请前端开发提供一下支持？

可以提供前端支持的。因为还涉及到产品的改动，可以入群和 @ZHAOYINRUI  寅锐沟通一下产品的最终的体验，包括这些指标放哪里等，确定好了之后就可以开始开发了。

**Comment by ZHAOYINRUI** [comment]
好的，这个需求我记录一下。在后续版本迭代中完善

**Comment by ZHAOYINRUI** [comment]
可以在Topic详情页->分区信息tab页。在表头增加：Sum of partition offsets、Sum of msgNum 统计
![image](https://user-images.githubusercontent.com/51046167/115987597-43989180-a5e8-11eb-9ed5-3cf45460654a.png)
在运维管控->集群详情->Broker信息tab页。在列表增加【Leader个数】数据列（支持排序）。
![image](https://user-images.githubusercontent.com/51046167/115987638-7e022e80-a5e8-11eb-8035-2e611ba6205c.png)

**Comment by ZHAOYINRUI** [comment]
那就辛苦老哥，后端开发完后，提一个pr。我们合并之后，在此基础上把开发前端页面～

**Comment by cobolbaby** [comment]
@ZHAOYINRUI 您给的UI呈现方式已经满足需求了，感谢。

另外:

- GET /api/v1/rd/clusters/:id/brokers 的接口返回值中包含了 **leaderCount: 449** 字段，所以前端列表只差一个显示出来了
- 而分区显示页面，可以通过计算属性把**endOffset**相加

**Comment by ZQKC** [comment]
> @ZHAOYINRUI 您给的UI呈现方式已经满足需求了，感谢。
> 
> 具体页面实现:
> 
> * GET /api/v1/rd/clusters/:id/brokers 的接口返回值中包含了 **leaderCount: 449** 字段，所以前端列表只差一个显示出来了
> * 而分区显示页面，Sum of partition offsets指标可以通过计算属性把**endOffset**相加

第一个已经具备，第二个暂时不考虑
