### ISSUE TITLE
https下部署重新登录会跳http的login

### ISSUE THREAD

**Issue by souzens** [didi/LogiKM#24]
容器部署在https下，
重启pod
重新登录会跳http的login
跳转失败，需要退出重新登录

<img width="1277" alt="bug" src="https://user-images.githubusercontent.com/35559209/83755384-170e1b00-a6a0-11ea-9cbf-8253ab865ebd.png">

**Comment by wangyacongii** [comment]
你好，请你试一下使用http访问，看是否会出现该问题

**Comment by ZQKC** [comment]
暂不支持https
