### ISSUE TITLE
接入集群优化，填写的ZK地址，具体是哪一个地址？

### ISSUE THREAD

**Issue by ZQKC** [didi/LogiKM#276]
接入集群优化，填写的ZK地址，具体是哪一个地址？

**Comment by Hongten** [comment]
这个应该和kafka集群配置里面的zookeeper地址一样吧

**Comment by ZQKC** [comment]
> 这个应该和kafka集群配置里面的zookeeper地址一样吧

嗯，是的。但是现在很多用户在接入集群的时候，只填写了ZK的IP:PORT的地址，没有填写后面的namespace，所以提示一下

**Comment by Hongten** [comment]
> 嗯，是的。但是现在很多用户在接入集群的时候，只填写了ZK的IP:PORT的地址，没有填写后面的namespace，所以提示一下
hmmm, 如果我在kafka配置里面配置的是`localhost:2181/kafka`，但是我在接入集群的时候填写` localhost:2181`，后面在logi-KM里面的操作，都会同步到zookeeper的根目录 `/`， 而不是 `/kafka`目录，可以这样理解吗？

**Comment by ZQKC** [comment]
> > > 这个应该和kafka集群配置里面的zookeeper地址一样吧
> > 
> > 
> > 嗯，是的。但是现在很多用户在接入集群的时候，只填写了ZK的IP:PORT的地址，没有填写后面的namespace，所以提示一下
> 
> hmmm, 如果我在kafka配置里面配置的是`localhost:2181/kafka`，但是我在接入集群的时候填写` localhost:2181`，后面在logi-KM里面的操作，都会同步到zookeeper的根目录 `/`， 而不是 `/kafka`目录，可以这样理解吗？

嗯嗯，可以这样理解。因为一个目录下面，可能就是一个集群。或者说两个集群都使用同一个ZK地址，但是是不同的目录，Logi-KM判断不出来，因此就直接用户填什么，就使用什么。

**Comment by Hongten** [comment]
> > > > 这个应该和kafka集群配置里面的zookeeper地址一样吧
> > > 
> > > 
> > > 嗯，是的。但是现在很多用户在接入集群的时候，只填写了ZK的IP:PORT的地址，没有填写后面的namespace，所以提示一下
> > 
> > 
> > hmmm, 如果我在kafka配置里面配置的是`localhost:2181/kafka`，但是我在接入集群的时候填写` localhost:2181`，后面在logi-KM里面的操作，都会同步到zookeeper的根目录 `/`， 而不是 `/kafka`目录，可以这样理解吗？
> 
> 嗯嗯，可以这样理解。因为一个目录下面，可能就是一个集群。或者说两个集群都使用同一个ZK地址，但是是不同的目录，Logi-KM判断不出来，因此就直接用户填什么，就使用什么。

hmm, 如果两边的配置不一样，导致的结果蛮严重的，即logi-KM配置的信息，在kafka集群里面可能不会生效。
这里需要做一个友好的提示才行。即一定要让user填写与kafka的server.properties里面的zookeeper地址
