### ISSUE TITLE
新建迁移任务，如果在同一天创建多个迁移任务，迁移任务名称一样，很难区分

### ISSUE THREAD

**Issue by Hongten** [didi/LogiKM#279]
新建迁移任务，如果在同一天创建多个迁移任务，迁移任务名称一样，很难区分
![image](https://user-images.githubusercontent.com/3076703/117391607-dad3e200-af22-11eb-8cd7-7ea32c406044.png)

建议：
看了source code，有合并的操作，但是我在测试过程中发现，对于同一个cluster下面的不同的topic进行创建迁移任务，每一个topic都会创建一个单独的迁移任务，并没有何必。
所以针对一个cluster下面的一个topic进行创建迁移任务，名称可以包含cluster name, topic name
e.g. 2021-05-07 数据迁移任务-cluster1-topicA

**Comment by Hongten** [comment]
并且发现创建时间和系统时间不一致
source code里面使用的是gmtCreate 作为创建时间。
`vo.setGmtCreate(elem.getGmtCreate().getTime());`
我们设置的任务开始时间则为系统时间
`vo.setBeginTime(elem.getBeginTime().getTime());`

**Comment by ZQKC** [comment]
@ZHAOYINRUI ，寅锐关注一下这个产品问题，看一下怎么优化比较合适

**Comment by Hongten** [comment]
再次查询了一下source code，获取到所有的迁移任务使用下面的SQL script。然而，每次创建迁移任务的时候，`gmt_create` 是不一样的。 因此，同一批任务聚合在一起，好像并不会生效，仍然会一条任务当作一个批次进行聚合。这样好像聚合的意义并没有体现出来。
`SELECT * FROM reassign_task_tab ORDER BY gmt_create DESC`

**Comment by ZQKC** [comment]
> 再次查询了一下source code，获取到所有的迁移任务使用下面的SQL script。然而，每次创建迁移任务的时候，`gmt_create` 是不一样的。 因此，同一批任务聚合在一起，好像并不会生效，仍然会一条任务当作一个批次进行聚合。这样好像聚合的意义并没有体现出来。
> `SELECT * FROM reassign_task_tab ORDER BY gmt_create DESC`

看了一下任务批量写DB的那个sql，那个sql少了对gmtCreate的赋值，因此导致同一批任务不能被聚合到一起。这块还是等产品@ZHAOYINRUI 来看一下怎么调整比较合适吧。之前设想是一批任务里面，可以迁移多个Topic。现在是变成了，一次性可以创建多个Topic迁移任务，每个任务还是一个Topic。

**Comment by ZHAOYINRUI** [comment]
嗯，这个地方后续会统一优化一下
