### ISSUE TITLE
如何连接带tls的zookeeper

### ISSUE THREAD

**Issue by xuanyunhui** [didi/LogiKM#28]
zookeeper配置了tlsSidecar通过TLS加密通信，怎么配置kafka-manager连接？

**Comment by ZQKC** [comment]
这块当前在界面上配置不了，得修改创建ZK客户端的代码才可以。这块我们后续看一下怎么支持加密的ZK，或者也欢迎提供解决方案或者代码等一起交流学习一下。

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题
