### ISSUE TITLE
region可用容量为零

### ISSUE THREAD

**Issue by opshongwu** [didi/LogiKM#289]
安装完成后，region可用容量显示为零，需要等待系统等待周期计划任务，可否实现手动一键加速或立即执行功能

**Comment by ZHAOYINRUI** [comment]
由于该周期任务的执行时间较长，故设置的执行间隔较长。后续，考虑下如何提升任务执行效率

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该问题，到时候提供一下操作的文档～
