### ISSUE TITLE
topic下线之后，创建与下线topic相同名称的topic会提示topic已存在报错信息，数据库找不到对应的记录，在全部topic栏目也能搜到

### ISSUE THREAD

**Issue by AllenWod** [didi/LogiKM#320]
![image](https://user-images.githubusercontent.com/22765507/120265651-07d1a580-c2d3-11eb-84c2-c6f934b80cc1.png)
![image](https://user-images.githubusercontent.com/22765507/120265669-0f914a00-c2d3-11eb-8475-04106639639c.png)
![image](https://user-images.githubusercontent.com/22765507/120265720-28016480-c2d3-11eb-8cea-106d46ee0aad.png)

**Comment by AllenWod** [comment]
km版本是2.4.2，Release部署

**Comment by ZQKC** [comment]
已在最新版本中修复～
