### ISSUE TITLE
LDAP不区分用户名大小写的情况下会造成重复创建帐号

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#326]
LDAP一般都会配置大小写不敏感，可能会造成重复新建帐号．

**Comment by ZQKC** [comment]
@ZHAOYINRUI 辛苦关注一下这些登录账号的设计上是否调整为大小写不敏感

**Comment by cobolbaby** [comment]
LDAP一般都能返回登陆用户的用户信息，建议采用返回信息中用户名称，而非采用输入值。

**Comment by cobolbaby** [comment]
@ZQKC PR什么时候可以被合并? 感觉近期维护力度不够。

**Comment by ZQKC** [comment]
> @ZQKC PR什么时候可以被合并? 感觉近期维护力度不够。

感谢老哥的贡献，最近在搞重构的事情，所以迭代节奏换缓了😂。这块对产品有变化，我催一下产品先，让产品看一下这样调整是否可以，然后再看一下代码啊。

**Comment by ZHAOYINRUI** [comment]
感谢贡献～，提出的需求我简单看了一下，确实是当前版本产品上需要改进的地方。@ZQKC 看看代码有没有什么问题，如果没什么问题的话，可以看着合一下pr。
后续，新版的logikm会接入logi日志套件，届时会使用logi统一的用户信息认证，到时候在用户信息认证这一块儿会有一个比较明显的优化

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该问题对应的PR～
