### ISSUE TITLE
EXPIRED_TOPIC_CONFIG规则能否新增一个topicPattern属性

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#327]
通过该属性来定义topic的正则匹配规则，来过滤掉一些虽然没有流量但是必须保留的topic？

**Comment by ZHAOYINRUI** [comment]
目前平台的做法是不会自动清理topic的。只会有运维人员手动清理。
至于长时间没有流量的topic，平台提供的功能是“通知topic负责人申请topic下线”

**Comment by cobolbaby** [comment]
@ZHAOYINRUI  明白，我的意思主要是说“资源治理”那块显示的Topic主要是依据EXPIRED_TOPIC_CONFIG规则而定的，但当前的判断规则比较单一，所以我想着能否丰富一点。

**Comment by ZHAOYINRUI** [comment]
嗯，目前的判断规则确实比较单一，在未来的迭代中也想丰富一下判断纬度，比如，除了考虑长期未使用的topic外，是否需要考虑治理仅为了测试而建的topic等。兄弟，如果有好的想法，也非常欢迎提出来，咱们一起探讨～

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下ISSUE对应的该PR～
