### ISSUE TITLE
DeleteMetrics task问题

### ISSUE THREAD

**Issue by Hongten** [didi/LogiKM#329]
当前这个task DeleteMetrics 会把7天的metric数据删除掉，但是在删除掉时候，sql里面有limit限制。
当采集的metrics数量远远大于limit数量的时候，会导致导致数据急剧膨胀。

我们做了一个测试，当我们的metrics数量大于100万以后，DeleteMetrics task删除的速度远远落后于创建速度，最终一个table的数据大小为754GB，并且还会继续增长。（table 名称有修改）

![image](https://user-images.githubusercontent.com/3076703/122548246-ae53cf80-d063-11eb-9919-2c037794ae19.png)

建议：移除sql里面limit限制。

**Comment by ZQKC** [comment]
现在是2分钟删除一次数据，一次删除3K条，这样相当于是Topic数大于1500的时候，就会出现瓶颈了，这块的限制确实设置的太小了。

如果提高频率，30秒删除一次，一次最多删除5W条数据，这样Topic数在10W以内，历史数据基本都可以正常删除。不知道这样的删除速度是否可以满足你们的实际需求。

这里限制单次删除速度是为了避免单次删除太多的数据导致MySQL的压力过大，包括说主从之间的压力等，一般情况下确实不会触发到该问题。

**Comment by Hongten** [comment]
这是我们采取的解决方案。
1. logi-km 这边把sql里面的limit限制移除，在logi-km里面只能查看7天（默认）的metric数据。这样减少了metrics数据，提高了查询速度。
2. 我们把kafka metrics的数据通过prometheus，最终呈现在grafana上面，更多的历史metrics信息，可以在grafana上面查看

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该问题，也优化一下相关的删除速度～
