### ISSUE TITLE
修改Topic所属应用之后，"我的Topic"会出现两条记录

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#338]
有图有真相:

<img width="1437" alt="屏幕快照 2021-05-09 上午1 42 01" src="https://user-images.githubusercontent.com/11460848/124487491-61048b80-dde1-11eb-9261-ba6d8066028e.png">

**Comment by ZQKC** [comment]
数据展示的粒度是应用+Topic维度的展示的，所以会有两条记录出现的情况

**Comment by cobolbaby** [comment]
关键是我已经把所属应用改了，为什么还有相应的记录呢？这个出于什么样的业务诉求呢？

**Comment by ZQKC** [comment]
> 关键是我已经把所属应用改了，为什么还有相应的记录呢？这个出于什么样的业务诉求呢？

所属应用修改了，但是权限还在的

**Comment by cobolbaby** [comment]
为啥权限不会被重置了呢？

**Comment by ZQKC** [comment]
> 迁移所属应用不会迁移权限吗？

不会，现在修改所属应用操作没有走工单流程，所以这块还会保留原先的权限。避免因为权限突然没了，导致正在生产和消费的客户端出问题。
