### ISSUE TITLE
是否支持Kafka 2.8.0 （without zookeeper）

### ISSUE THREAD

**Issue by joyexpr** [didi/LogiKM#339]
kafka在4月发布了2.8.0版本，终于去掉了zookeeper依赖，请问Logi-KafkaManager现在是否支持2.8.0版本（无zookeeper）？ 如还未支持（看到demo中接入集群还需要配置zookeeper地址的参数），请问有无规划尽快支持？

**Comment by ZQKC** [comment]
> kafka在4月发布了2.8.0版本，终于去掉了zookeeper依赖，请问Logi-KafkaManager现在是否支持2.8.0版本（无zookeeper）？ 如还未支持（看到demo中接入集群还需要配置zookeeper地址的参数），请问有无规划尽快支持？

今年暂无计划支持无ZK模式的2.8版本，最快估计得明年了。原因一：当前无ZK模式的版本刚刚出来，一些功能还不支持，真正生产中使用的用户估计也不多，所以考虑等版本稳定之后，再进行支持。原因二：现在有一些使用Kafka过程中，更重要的痛点功能需要进行开发。
