### ISSUE TITLE
添加集群成功，但是Broker数及Topic数都为0 —— ZK连接处于SUSPENDED状态

### ISSUE THREAD

**Issue by ZQKC** [didi/LogiKM#34]
如果连接ZK没有成功，或者中间出现了ZK连接的状态发生变化的情况，则会导致一些ZK的事件丢失，比如监听不到Topic的创建或者Broker的上线事件

**Comment by YJF1002** [comment]
如果集群中已经有topic了，只要配置了集群，会自动获取到集群的topic吗？

**Comment by ZQKC** [comment]
会的
