### ISSUE TITLE
登陆接入LDAP之后，用户信息只有用户的唯一标示(工号)，而缺少其他描述信息(邮箱)

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#346]
因为用户只有工号信息，所以在赋权等诸多操作上不是很直观，人也比较难记住工号和“人”的对应关系，大家还是习惯了采用邮箱或者人名的方式进行辨识。

<img width="997" alt="屏幕快照 2021-07-07 下午11 21 46" src="https://user-images.githubusercontent.com/11460848/124787073-d22b7680-df7a-11eb-8d44-39b56d5307a7.png">

所以是否考虑扩展一下用户的信息？

**Comment by ZQKC** [comment]
> 因为用户只有工号信息，所以在赋权等诸多操作上不是很直观，人也比较难记住工号和“人”的对应关系，大家还是习惯了采用邮箱或者人名的方式进行辨识。
> 
> <img alt="屏幕快照 2021-07-07 下午11 21 46" width="997" src="https://user-images.githubusercontent.com/11460848/124787073-d22b7680-df7a-11eb-8d44-39b56d5307a7.png">
> 
> 所以是否考虑扩展一下用户的信息？

可以的，老哥有兴趣的话，欢迎来个PR啊😊

**Comment by ZQKC** [comment]
近期2.6.0版本我们处理一下该ISSUE及PR
