### ISSUE TITLE
LogiKM对接夜莺监控时告警规则无效的问题

### ISSUE THREAD

**Issue by PengShuaixin** [didi/LogiKM#354]
## 问题描述
在KM里面成功创建告警规则的情况下，夜莺监控系统里面在达到触发规则的情况下，不能正常报警

## 原因初步分析
分析方法`com.xiaojukeji.kafka.manager.monitor.component.n9e.N9eService#sinkMetrics`中的请求发给夜莺的监控指标，数据如下：
```
[{"metric":"online-kafka-topic-msgIn","nid":"1","step":60,"tags":"cluster=TAGTIC_KAFKA,topic=events","timestamp":1626337144,"value":0.0},{"metric":"online-kafka-topic-bytesIn","nid":"1","step":60,"tags":"cluster=TAGTIC_KAFKA,topic=events","timestamp":1626337144,"value":0.0},{"metric":"online-kafka-topic-bytesRejected","nid":"1","step":60,"tags":"cluster=TAGTIC_KAFKA,topic=events","timestamp":1626337144,"value":0.0},{"metric":"online-kafka-topic-msgIn","nid":"1","step":60,"tags":"cluster=TAGTIC_KAFKA,topic=__consumer_offsets","timestamp":1626337144,"value":2.964393875E-314},{"metric":"online-kafka-topic-bytesIn","nid":"1","step":60,"tags":"cluster=TAGTIC_KAFKA,topic=__consumer_offsets","timestamp":1626337144,"value":2.964393875E-314},{"metric":"online-kafka-topic-bytesRejected","nid":"1","step":60,"tags":"cluster=TAGTIC_KAFKA,topic=__consumer_offsets","timestamp":1626337144,"value":0.0}]
```
如上数据，我们能看到`tags`里面的数据为`cluster=TAGTIC_KAFKA`;  

再看`com.xiaojukeji.kafka.manager.monitor.component.n9e.N9eService#createStrategy`方法，发现向夜莺发送创建告警规则时，请求数据如下：
```
{"alert_dur":60,"alert_upgrade":{"duration":60,"groups":[],"level":1,"users":[]},"callback":"","category":2,"converge":[300,1],"enable_days_of_week":[0,1,2,3,4,5,6,7],"enable_etime":"23:59","enable_stime":"00:00","excl_nid":[],"exprs":[{"eopt":"<","func":"all","metric":"online-kafka-topic-msgIn","params":[1],"threshold":0}],"name":"测试-A","need_upgrade":0,"nid":1,"notify_group":[1],"notify_user":[],"priority":3,"recovery_dur":0,"recovery_notify":0,"tags":[{"tkey":"topic","topt":"=","tval":["events"]},{"tkey":"cluster","topt":"=","tval":["内网集群"]}]}
```
如上数据，发现`{"tkey":"cluster","topt":"=","tval":["内网集群"]}`中`cluster`的标签值为`内网集群`;  

其中，`TAGTIC_KAFKA`和`内网集群`的关系在KM中如图：  
![0](https://user-images.githubusercontent.com/42090337/125757123-8f238433-8c38-450c-812e-c887ebcb4e20.png)

在夜莺的界面中能看到如下的情况：  

![1](https://user-images.githubusercontent.com/42090337/125757834-77890e5f-40e9-40ee-8737-213004bcb0f8.png)

![2](https://user-images.githubusercontent.com/42090337/125757874-2e98d0ae-be48-4e4c-9233-abd3f9ec96e9.png)

根据以上分析得出，导致告警无法触发的原因就是，KM在创建告警规则时使用的cluster标签是**集群名称**，而向夜莺上传监控指标时使用的cluster标签是**集群标识**，由此就导致告警系统在使用cluster标签过滤数据时出现了问题，最终导致告警规则在满足条件的情况下也无法触发。

## 临时解决方案
在夜莺监控页面，修改cluster过滤标签，从上图改成如下：
![3](https://user-images.githubusercontent.com/42090337/125759257-71466fd4-622a-4e6e-894f-6b5652331d24.png)
![4](https://user-images.githubusercontent.com/42090337/125759991-8c5f037f-5087-4921-9232-304c2ce7765d.png)

**Comment by ZQKC** [comment]
使用的版本是？之前旧版本在创建监控策略的时候，创建了机器相关的策略，应该是机器无关的，这块可以检查一下。

**Comment by PengShuaixin** [comment]
KM的版本是2.4.2，编译打包的代码是master分支最新的代码，夜莺版本是4.0.1

**Comment by PengShuaixin** [comment]
在KM页面上创建之后，告警规则展示如下：
![0](https://user-images.githubusercontent.com/42090337/125906677-b186d67f-2e69-4164-9fdc-f8d854ca6801.png)

![1](https://user-images.githubusercontent.com/42090337/125906578-f4bcc371-8db7-4704-b681-10c870fc51d4.png)

**Comment by ranqiqiang** [comment]
这个tag 监控，必须要接入夜莺吗？

**Comment by ZQKC** [comment]
可以再对照一下夜莺平台上的指标，看是否满足触发条件，如果满足但是没有触发，估计得问一下夜莺相关的同学。具体的欢迎入群(README中有)沟通～

**Comment by ZQKC** [comment]
可以再对照一下夜莺平台上的指标，看是否满足触发条件，如果满足但是没有触发，估计得问一下夜莺相关的同学。具体的欢迎入群(README中有)沟通～

**Comment by ZQKC** [comment]
无更多反馈，关闭该问题，也欢迎入群交流～
