### ISSUE TITLE
Topic 无法自动审批

### ISSUE THREAD

**Issue by yangvipguang** [didi/LogiKM#357]
配置文件中topic  和 app  自动审批都开启了。应用申请自动审批可以的，但是Topic 申请没有反应。
![image](https://user-images.githubusercontent.com/11416887/126974888-febc2868-41ff-4bfd-9704-85340460668f.png)
![image](https://user-images.githubusercontent.com/11416887/126974941-ffa3d940-0604-4745-892d-f1760f47218a.png)
下面是topic 自动审批一直无反应。
![image](https://user-images.githubusercontent.com/11416887/126975007-0dfbeb24-f197-48b3-b8b9-a376895eb130.png)

**Comment by ZQKC** [comment]
> 配置文件中topic 和 app 自动审批都开启了。应用申请自动审批可以的，但是Topic 申请没有反应。
> ![image](https://user-images.githubusercontent.com/11416887/126974888-febc2868-41ff-4bfd-9704-85340460668f.png)
> ![image](https://user-images.githubusercontent.com/11416887/126974941-ffa3d940-0604-4745-892d-f1760f47218a.png)
> 下面是topic 自动审批一直无反应。
> ![image](https://user-images.githubusercontent.com/11416887/126975007-0dfbeb24-f197-48b3-b8b9-a376895eb130.png)

自动化审批除了开启配置之外，还需要依赖region的容量是否正常，如果region容量满了，那么自动化审批也是会失败的

**Comment by yangvipguang** [comment]
正常的
![image](https://user-images.githubusercontent.com/11416887/127799894-c39b39bf-433c-4f68-8fd1-42501ec6a416.png)

**Comment by ZQKC** [comment]
不好意思，现在才回复。请问这个问题现在是否已经解决了？方便的话，入用户群交流一下，以便尽快解决该问题。

**Comment by ZQKC** [comment]
无更多反馈，关闭issue
