### ISSUE TITLE
是否可以将前端的插件由npm改成yarn，npm打包太容易失败了

### ISSUE THREAD

**Issue by chenzhongyu11** [didi/LogiKM#367]
配置如下，经本地试验可以打包成功

               <execution>
                        <id>install node and yarn</id>
                        <goals>
                            <goal>install-node-and-yarn</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v12.20.0</nodeVersion>
                            <yarnVersion>v1.9.4</yarnVersion>
                            <nodeDownloadRoot>http://npm.taobao.org/mirrors/node/</nodeDownloadRoot>
                            <yarnDownloadRoot>https://npm.taobao.org/mirrors/yarn/</yarnDownloadRoot>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn install</id>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn run prod-build</id>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                        <configuration>
                            <arguments>run prod-build</arguments>
                        </configuration>
                    </execution>

**Comment by lucasun** [comment]
mvn打包插件是最普遍认可实现，可以根据自身的网络环境配置不同的前端包管理工具～
