### ISSUE TITLE
告警接入夜莺不成功

### ISSUE THREAD

**Issue by zhenglin305** [didi/LogiKM#369]
夜莺版本：4.0.3
kafka manager版本：2.4.3
部署在K8S里

kafka manager配置：
![image](https://user-images.githubusercontent.com/66998320/131610017-d383972b-1290-47bc-9bc7-8221864fb1c4.png)

获取不到baoji报警接收组，日志报错：
![image](https://user-images.githubusercontent.com/66998320/131609932-019df87b-6d56-4982-b5d8-c4ccbd62246b.png)

请问是哪里的问题呢

**Comment by zhushanwei** [comment]
三个端口都设置成8000 试试看呢

**Comment by zhenglin305** [comment]
试过了，不行的，好像是夜莺V4之后把服务合并了，只有server服务了，应该是不支持了，希望km这边能跟上节奏

**Comment by zhushanwei** [comment]
哦 我用的是夜莺4.0.1是可以的
