### ISSUE TITLE
建议优化部署打包

### ISSUE THREAD

**Issue by melin** [didi/LogiKM#371]
目前打包成一个jar，不方便部署，启动进程名都是jar，如果启动多个进程也不方面区分，需要单独写部署脚本，建议提供类似tomcat，kafka 这样软件的分发包，包含lib, conf, bin目录，自带启动脚本，
具体参考我的项目中打包方式，https://github.com/melin/dzlog

**Comment by ZHAOYINRUI** [comment]
好的，兄弟的建议我们近期关注一下～

**Comment by ZQKC** [comment]
已在最新2.5.0版本优化～
