### ISSUE TITLE
支持接入多台LDAP Server

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#374]
大厂往往会根据地域切分域控Server，所以要想支持多地的用户访问，就得支持接入多台LDAP Server

**Comment by ZHAOYINRUI** [comment]
这部分内容暂时还没有列入我们的迭代中来，如果兄弟感兴趣的话欢迎提pr参与共建～

**Comment by ZQKC** [comment]
这块我们会按照地域，或者说数据中心部署LogiKM，然后通过前端页面去做数据中心或者地域的切换。因此不同的LogiKM的配置的时候，配置不同地域的Ldap服务即可。

**Comment by ZQKC** [comment]
> 

辛苦重新提个issue，我们后续单独跟进一下

**Comment by cobolbaby** [comment]
@ZQKC 之前有个 ISSUE 与此相关，可以重开一下 https://github.com/didi/LogiKM/issues/347
