### ISSUE TITLE
"集群概览"下查看最近7天"历史流量"的时候，Tooltip中的时间只包含日期

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#379]
![2021-09-22 09-51-55屏幕截图](https://user-images.githubusercontent.com/11460848/134271461-d98c8d6f-34ee-4e5e-a242-47eb7ac44ae0.png)

当选择的时间跨度大一点时，比如7天，Tooltip中的时间只包含日期，不包含时间，查看起来不太方便。

**Comment by ZHAOYINRUI** [comment]
好的，这个建议我们近期关注一下

**Comment by ZQKC** [comment]
已在最新2.5.0版本修复
