### ISSUE TITLE
提供Cron任务说明

### ISSUE THREAD

**Issue by Huyueeer** [didi/LogiKM#381]
### 建议对程序中涉及到的Cron任务进行详细说明
方便对具体任务自定义执行频度，也有利于运维人员定位此服务后台任务会涉及到的网络流量和DB读写情况。

**Comment by ZHAOYINRUI** [comment]
近期暂时还没有这类需求的规划，不过未来是想要把平台中包含的各项任务都展示出来，欢迎兄弟提pr参与到共建中来。

**Comment by ZQKC** [comment]
近期小版本我们补充一下cron任务的说明
