### ISSUE TITLE
"运维管控--集群列表--Region信息"显示问题

### ISSUE THREAD

**Issue by Huyueeer** [didi/LogiKM#382]
"预估容量"是否不应该包含单位(MB/s)

![image](https://user-images.githubusercontent.com/40758588/134470637-5c95858c-c9a2-4faf-978f-0048b98a6c68.png)

**Comment by ZQKC** [comment]
> "预估容量"是否不应该包含单位(MB/s)
> 
> ![image](https://user-images.githubusercontent.com/40758588/134470637-5c95858c-c9a2-4faf-978f-0048b98a6c68.png)

是需要有的，在2.x版本上，容量主要考虑的是流量流量，所以这里是MB/s。这里觉得不需要有的原因是？
