### ISSUE TITLE
topic采样中文乱码问题

### ISSUE THREAD

**Issue by duchang9264** [didi/LogiKM#385]
![image](https://user-images.githubusercontent.com/34643603/134830122-bcda69e4-45c6-4f24-ad19-8feef0d3a1ac.png)

内容中文乱码，kafka生产和消费序列化，消费展示中文正常，监控平台中文乱码

**Comment by ZHAOYINRUI** [comment]
好的，这个问题我们近期关注一下～

**Comment by ZQKC** [comment]
已在最新2.5.0版本中修复
