### ISSUE TITLE
ERROR c.x.k.manager.common.utils.jmx.JmxConnectorWrap 

### ISSUE THREAD

**Issue by zhangxinjian123** [didi/LogiKM#390]
9 [Collect-Metrics-Thread-1-56] ERROR c.x.k.manager.common.utils.jmx.JmxConnectorWrap - JMX connect exception, host:kafka001 port:8868.
java.rmi.ConnectException: Connection refused to host: xxxx.xxxx.xxx.xxxx; nested exception is: 
	java.net.ConnectException: Connection timed out (Connection timed out)

**Comment by ZHAOYINRUI** [comment]
好的，这个问题我们近期关注一下～

**Comment by ZHAOYINRUI** [comment]
该问题已修复，已发布在最新的版本中～

**Comment by ZQKC** [comment]
这个问题和Kafka的JMX配置直接相关，如果再出现，欢迎入群(README中有)沟通，该Issue先关闭了
