### ISSUE TITLE
期望tomcat依赖包升级到8.5.72

### ISSUE THREAD

**Issue by trockxi** [didi/LogiKM#392]
https://nosec.org/home/detail/4888.html
基于安全考虑，需要依赖包也进行升级，辛苦大佬升级

**Comment by ZQKC** [comment]
> https://nosec.org/home/detail/4888.html 基于安全考虑，需要依赖包也进行升级，辛苦大佬升级

好的，我们近期看一下，也欢迎老哥贡献PR 😊
