### ISSUE TITLE
Docker运行报错

### ISSUE THREAD

**Issue by wuare** [didi/LogiKM#398]
Dockerfile里运行命令指定了参数--spring.config.location=application.yml，而application.yml是在jar包里的，应该是--spring.config.location=classpath:/application.yml这样，或者去掉这个参数吧？

**Comment by wuare** [comment]
@fengxsong

**Comment by ZQKC** [comment]
近期的2.6.0版本我们看一下这个问题

**Comment by ZQKC** [comment]
> --spring.config.location=application.yml

这块是不是只是一个例子，--spring.config.location=application.yml 只是指定一下。

请问这块的错误除了这个是否还有其他的？

**Comment by wuare** [comment]
https://github.com/didi/LogiKM/blob/master/container/dockerfiles/Dockerfile#L28
@ZQKC 这一行有个spring.config.location的参数，用docker启动的时候好多配置找不到，会报错
我改成--spring.config.location=classpath:/application.yml这样就可以了

**Comment by ZQKC** [comment]
> https://github.com/didi/LogiKM/blob/master/container/dockerfiles/Dockerfile#L28

是不是因为在当前目录下面没有application.yml这个文件导致的，是否加一下这个文件就可以了？

**Comment by wuare** [comment]
application.yml这个文件在jar包里，把spring.config.location这个启动参数去掉应该就可以了，spring会默认找jar包里的application.yml这个文件
@ZQKC

**Comment by wuare** [comment]
你可以测试一下，我当时用这个dockerfile修改配置，直接启动，会报错
你看看你那儿报错吗？
@ZQKC

**Comment by ZQKC** [comment]
> application.yml这个文件在jar包里，把spring.config.location这个启动参数去掉应该就可以了，spring会默认找jar包里的application.yml这个文件 @ZQKC

这样是不是有点不友好，因为在jar包里面不能自定义相关的配置，放在外面方便配置的变更

**Comment by ZQKC** [comment]
> 你可以测试一下，我当时用这个dockerfile，直接启动，会报错 你看看你那儿报错吗？ @ZQKC

好的，我也试一下，看着应该会缺少一些文件
