### ISSUE TITLE
当集群异常时，如何查看 offline 状态的分区以明确受影响的Topic

### ISSUE THREAD

**Issue by cobolbaby** [didi/LogiKM#438]
如题

**Comment by ZQKC** [comment]
这块预计3.0版本会涉及，2.x版本当前不具备，后续可以考虑一下。这块可以告知一下具体触发使用的场景么？看看在当前现状下，是否有其他解决方式

**Comment by cobolbaby** [comment]
就是某个节点下线之后，可能会影响部分Topic的使用，此时运维侧需要明确影响面。

**Comment by ZQKC** [comment]
> 就是某个节点下线之后，可能会影响部分Topic的使用，此时运维侧需要明确影响面。

感谢。看知识星球上已经有相关交流了，可以使用脚本先看一下，后续我们3.0版本会有一个大盘来统计改信息。当前问题先进行关闭。
