### ISSUE TITLE
并非所有mbean 都有带有topic tag

### ISSUE THREAD

**Issue by yws-tracy** [didi/LogiKM#455]
getTopicMetrics 中

                        new ObjectName(mbeanV2.getObjectName(kafkaVersion.getVersionNum()) + ",topic=" + topicName)
并不是所有mbean 都有topic维度吧？ 比如kafka.network:type=RequestMetrics,name=RequestQueueTimeMs 是没有topic 维度的, 会导致获取抛异常， 界面上显示为空

**Comment by ZQKC** [comment]
> getTopicMetrics 中
> 
> ```
>                     new ObjectName(mbeanV2.getObjectName(kafkaVersion.getVersionNum()) + ",topic=" + topicName)
> ```
> 
> 并不是所有mbean 都有topic维度吧？ 比如kafka.network:type=RequestMetrics,name=RequestQueueTimeMs 是没有topic 维度的, 会导致获取抛异常， 界面上显示为空

这个方法是getTopicMetrics，因此要求传入的参数就需要带有Topic Tag，kafka.network:type=RequestMetrics,name=RequestQueueTimeMs 这个并非Topic的Metrics，因此获取这个指标并不会使用该方法。

这块是遇到什么问题了么？

**Comment by yws-tracy** [comment]
是的， 这块界面显示的时候是没有指标的，一开始以为是哪出现问题了，  原生kafka 有些metrics是没有 topic 维度的，应该是滴滴这边增加了一些topic维度的指标,
