### ISSUE TITLE
为什么我看不到流量的监控信息？

### ISSUE THREAD

**Issue by lushenao** [didi/LogiKM#458]
添加集群成功 能看到topic的信息，但是看不到broker的监控信息，都是no data

**Comment by lushenao** [comment]
![image](https://user-images.githubusercontent.com/59196347/151285849-53c29ba2-42e0-459d-b081-37b67d27792b.png)

**Comment by ZQKC** [comment]
可以看一下是不是JMX开启的有问题，具体可以看一下日志和README中的FAQ

**Comment by ZQKC** [comment]
长期无反馈，关闭issue
