### ISSUE TITLE
创建topic流程 app和topic以及集群绑定关系困惑

### ISSUE THREAD

**Issue by yws-tracy** [didi/LogiKM#462]
LogiManager创建topic流程有个困惑：  一开始选择集群， 再选择应用，可选的集群包括共享集群，以及自己是负责人的集群， 对应的关系是： 人-> app  app-> 集群， 如果先选择了一个专享app的集群，但下面选择app又没有选择该专享的app，而是其他app， 这样是不是这个topic 在属于其他app情况下仍然放在了专享app的集群？

**Comment by ZQKC** [comment]
1、app是集群无关的，可以将app理解为Kafka里面的一个账号，然后所有资源的归属，都是挂在app下的。
2、资源归属于某个app，但是不代表这个资源就只能给这个app使用。
3、独享，独立等类型的Kafka集群并非完全交付app负责人去使用以及管理，负责人也很难控制或者限定只有某些app可以使用，因此设计为只要可以看到，就允许你使用。
4、先选择应用，再选择具体集群，然后进行相关的限制也是可行的，也如你说的，这样资源及权限上会更加清晰。但是如上提到的，需要app负责人管理好相关app集合，仅有一个app可以使用该集群，在业务上一般是不能满足要求的。
5、2.x版本在用户权限体系上会有一些局限，包括你说的场景。 在未来3.x版本上，会引入角色，权限点等内容，到时候会更加灵活。

**Comment by ZQKC** [comment]
1、app是集群无关的，可以将app理解为Kafka里面的一个账号，然后所有资源的归属，都是挂在app下的。
2、资源归属于某个app，但是不代表这个资源就只能给这个app使用。
3、独享，独立等类型的Kafka集群并非完全交付app负责人去使用以及管理，负责人也很难控制或者限定只有某些app可以使用，因此设计为只要可以看到，就允许你使用。
4、先选择应用，再选择具体集群，然后进行相关的限制也是可行的，也如你说的，这样资源及权限上会更加清晰。但是如上提到的，需要app负责人管理好相关app集合，仅有一个app可以使用该集群，在业务上一般是不能满足要求的。
5、2.x版本在用户权限体系上会有一些局限，包括你说的场景。 在未来3.x版本上，会引入角色，权限点等内容，到时候会更加灵活。
