### ISSUE TITLE
ApplyClusterOrder handleOrderDetail 处理直接返回sucess

### ISSUE THREAD

**Issue by yws-tracy** [didi/LogiKM#463]
class: ApplyClusterOrder  
public ResultStatus handleOrderDetail(OrderDO orderDO,
                                          OrderHandleBaseDTO orderHandleBaseDTO,
                                          String userName) {
        return ResultStatus.SUCCESS;
    }

为啥直接返回sucess了？  貌似没看到处理逻辑

**Comment by ZQKC** [comment]
> class: ApplyClusterOrder public ResultStatus handleOrderDetail(OrderDO orderDO, OrderHandleBaseDTO orderHandleBaseDTO, String userName) { return ResultStatus.SUCCESS; }
> 
> 为啥直接返回sucess了？ 貌似没看到处理逻辑

集群申请的工单流程，仅仅是给用户一个表达述求的入口。实际的集群搭建或者说创建，需要管理员手动操作好给他。
