### ISSUE TITLE
请问怎么对接v5版本的夜莺？

### ISSUE THREAD

**Issue by One1W** [didi/LogiKM#466]
目前看对接文档
mon:
      base-url: http://127.0.0.1:8006
    # 夜莺 transfer上传服务 地址
    sink:
      base-url: http://127.0.0.1:8008
    # 夜莺 rdb资源服务 地址
    rdb:
      base-url: http://127.0.0.1:80
这几个端口都没有了 token也没了 新版v5的夜莺应该怎么对接呢

**Comment by ZQKC** [comment]
不支持夜莺的v5版本
