### ISSUE TITLE
拉js 文件太慢

### ISSUE THREAD

**Issue by yws-tracy** [didi/LogiKM#467]
第一次启动浏览器拉取vendor.js 7M的文件要40s  影响体验 怎么解一下呢

**Comment by lucasun** [comment]
可以根据自身环境在splitChunks中添加maxSize控制包的大小，权衡包数量和大小的利弊，例如设置maxSize: 10000000

**Comment by lucasun** [comment]
> 第一次启动浏览器拉取vendor.js 7M的文件要40s 影响体验 怎么解一下呢

可以根据自身环境在splitChunks中添加maxSize控制包的大小，权衡包数量和大小的利弊，例如设置maxSize: 10000000
