### ISSUE TITLE
消费者组增加展示完整id

### ISSUE THREAD

**Issue by taoyantu** [didi/LogiKM#468]
通过Logstash消费Kafka时，在消费者id有ip地址信息，可以查看消费者的ip。
这个对于运维操作非常重要，能否增加该功能？
有没有别的方式，能查看消费者IP的信息？

**Comment by ZQKC** [comment]
> 通过Logstash消费Kafka时，在消费者id有ip地址信息，可以查看消费者的ip。 这个对于运维操作非常重要，能否增加该功能？ 有没有别的方式，能查看消费者IP的信息？

没有大盘页面，不过在Topic详情，消费者信息，消费详情里面有些情况是可以看到的。
