### ISSUE TITLE
集成夜莺V4以后，告警在Logi-KM中为空

### ISSUE THREAD

**Issue by meng7even** [didi/LogiKM#480]
### 版本信息
- Logi-KM v2.6
- n9e v4.0.3

夜莺的报警历史中，可以收到告警。但是LogiKM监控告警中的告警历史为空。
- Logi-KM
![image](https://user-images.githubusercontent.com/47548690/158575308-8c756a6a-604e-4b04-a221-73ea0133280d.png)

- n9e
![image](https://user-images.githubusercontent.com/47548690/158575406-cd91b29b-9e16-4a1c-b8b6-612d3e0bb90d.png)

**Comment by ZQKC** [comment]
仅将指标信息上报夜莺，告警历史暂未调用夜莺接口获取，老哥有兴趣的话，欢迎补充这部分功能

**Comment by ZQKC** [comment]
无更多反馈，关闭该issue
