### ISSUE TITLE
logi km 2.6 配置zk提示zookeeper connect failed code: 8020 错误

### ISSUE THREAD

**Issue by thomasgogo** [didi/LogiKM#493]
logi km 版本: [v2.6.0](https://github.com/didi/Logi-KafkaManager/releases)
添加集群节点出错,logi km部署在开发环境,另外一个zk+kakfa 集群部署在欧洲节点;网络通过vpn打通,两者之间的延迟在200-300ms之间;不知道是不是延迟比较大的原因,导致不能把这个zk+kafka集群添加上;请问下,有没有其他的办法可以解决这个问题.

**Comment by thomasgogo** [comment]
添加后的报错信息如下:
{
    "data": null,
    "message": "zookeeper connect failed",
    "tips": null,
    "code": 8020
}

**Comment by ZQKC** [comment]
> logi km 版本: [v2.6.0](https://github.com/didi/Logi-KafkaManager/releases) 添加集群节点出错,logi km部署在开发环境,另外一个zk+kakfa 集群部署在欧洲节点;网络通过vpn打通,两者之间的延迟在200-300ms之间;不知道是不是延迟比较大的原因,导致不能把这个zk+kafka集群添加上;请问下,有没有其他的办法可以解决这个问题.

1、可以直接按照cluster表的格式，直接插入一条数据。
2、建议将KM也部署在欧洲，然后对集群进行接入等，这样后续的指标采集等等都会相对稳定一些。

**Comment by thomasgogo** [comment]
OK
