### ISSUE TITLE
用户权限管理，根据用户隔离当前用户下的topic

### ISSUE THREAD

**Issue by frankYu001** [didi/LogiKM#73]
每个用户都能看到所有的topic，然后操作，不安全，希望新增topic跟据用户进行隔离

**Comment by ZQKC** [comment]
是能看到所有的Topic及进行信息的查看，但是很多地方是操作不了的，这个是否满足需求呢？或者说期望的隔离程度是？

**Comment by cell13** [comment]
> 每个用户都能看到所有的topic，然后操作，不安全，希望新增topic跟据用户进行隔离

当前的设计模式是根据应用做的限制，topic关联应用。看到应用是有密码，还没弄懂怎么用

**Comment by ZQKC** [comment]
1、应用可以理解为Kafka里面的一个账号。
2、我们内部会依据这个账号进行安全管控，开源密码的用途较弱。更多细节可以入群交流。
