### ISSUE TITLE
逻辑集群创建、管理与应用关联及显示的问题

### ISSUE THREAD

**Issue by cell13** [didi/LogiKM#86]
问题：
1、逻辑集群是和应用关联的，集群管理这块能把关联的应用也显示出来吗。因为用户当前是和应用关联的，如果新增加逻辑集群和应用关联，集群管理的部分可能就莫名多了一些集群。增加应用信息，可以使信息更加明确，方便用户管理。

- 在我的topic部分是显示了关联的应用。

- 在全部topic部分关联应用信息又没了

2、运维管控->物理集群-》新增逻辑集群，都是要关联应用。按照设计逻辑共享集群是不属于任何应用的，需要修改创建逻辑共享集群的时候，应该不需要选择应用。

**Comment by ZQKC** [comment]
@ZHAOYINRUI  辛苦看一下这个需求

**Comment by ZQKC** [comment]
3.x版本返璞归真，没有这些复杂的概念
